// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCauwjpvN4AR8EKWbKxV0bgiEZIpzQilIo',
    appId: '1:984650402792:web:37f5f1fdd257f69371325d',
    messagingSenderId: '984650402792',
    projectId: 'activity-gen',
    authDomain: 'activity-gen.firebaseapp.com',
    storageBucket: 'activity-gen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8ZLwz0x13aQdsZsfqQYOZGf7YSBndBs',
    appId: '1:984650402792:android:5fa6895c0523b2bd71325d',
    messagingSenderId: '984650402792',
    projectId: 'activity-gen',
    storageBucket: 'activity-gen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGjDr6XbWLsHZ76WJS4-uAHg805-Zzh8',
    appId: '1:984650402792:ios:bfa473c189fe1fba71325d',
    messagingSenderId: '984650402792',
    projectId: 'activity-gen',
    storageBucket: 'activity-gen.appspot.com',
    iosBundleId: 'com.example.activityGen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGjDr6XbWLsHZ76WJS4-uAHg805-Zzh8',
    appId: '1:984650402792:ios:1cd5d2726726056371325d',
    messagingSenderId: '984650402792',
    projectId: 'activity-gen',
    storageBucket: 'activity-gen.appspot.com',
    iosBundleId: 'com.example.activityGen.RunnerTests',
  );
}
